name: Node CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm
        run: npm i -g npm
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
